-- RETIRED / NO-OP. Do not restore or execute an outdated version of the
-- Vinterro One historical corporate-domain first-touch guard.
-- PR #125 contained a partial domain check that omitted secondary contact emails.
-- Full replacement: supabase/vinterro-first-touch-domain-review-complete-20261009.sql
-- PR #126 applied live via migration vinterro_first_touch_domain_review_all_aliases_20261009.
-- This file intentionally contains NO EXECUTABLE SQL to prevent regressions
-- if a future deployment pipeline scans all supabase/*.sql files.
