#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

AGENTS = [
    "@Orchestrator", "@UpstreamIntelligence", "@ShopifyExpert", "@WordPressExpert", "@WixExpert",
    "@DragDrop", "@VinterroDigital", "@AyvalıkVibes", "@GoAyvalık", "@ScreenshotToCode",
    "@RealAsset", "@PixelMatch", "@UXEnhancement", "@ProductionQA", "@SEOExpert",
    "@SocialMediaExpert", "@CreativeDesignExpert", "@WebAppExpert", "@SecurityExpert",
    "@PerformanceExpert", "@AgentMCPExpert",
]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def has_heading(text: str, level: str, agent: str) -> bool:
    return bool(re.search(rf"(?m)^{re.escape(level)}\s+(?:\d+\.\s+)?{re.escape(agent)}\s*$", text))


def build_scoreboard() -> tuple[str, bool]:
    stable = read("docs/standards/STABLE_AGENT_CORE.md")
    sources = read("docs/research/AGENT_SOURCE_PACKS.md")
    bench = read("docs/evals/WORLD_CLASS_AGENT_BENCHMARK_SUITE.md")
    registries = read("docs/standards/AGENT_REGISTRY.md") + "\n" + read("docs/standards/DOMAIN_EXPERT_REGISTRY.md")
    codex = read(".codex/config.toml")
    research = read("docs/standards/WORLD_CLASS_AGENT_RESEARCH.md")

    global_research_gate = (
        "WORLD_CLASS_AGENT_RESEARCH.md" in stable
        and "WORLD_CLASS_AGENT_RESEARCH.md" in codex
        and "world" in research.lower()
        and "benchmark" in research.lower()
    )

    rows = []
    all_ok = True
    for agent in AGENTS:
        checks = {
            "stable": f"`{agent}`" in stable,
            "source_pack": has_heading(sources, "#", agent),
            "championship": has_heading(bench, "###", agent),
            "routing": has_heading(registries, "##", agent),
            "research_gate": global_research_gate,
        }
        score = sum(20 for passed in checks.values() if passed)
        ok = all(checks.values())
        all_ok &= ok
        rows.append((agent, score, ok, checks))

    lines = [
        "# Ercan OS — Agent Scoreboard",
        "",
        "Status: generated structural-readiness audit",
        "Audit date: 2026-08-31",
        f"Stable identities checked: **{len(AGENTS)}**",
        "",
        "This scoreboard measures **static governance/readiness only**. It does not claim behavioral superiority, benchmark wins, or world-best status. Runtime/tool-use/coding/browser/creative/security benchmark results remain `NOT_RUN` until executed in a reproducible harness with an independent evaluator.",
        "",
        "## Static readiness rubric",
        "",
        "Each item is worth 20 points: stable-core registration, dedicated source pack, agent-specific championship scenario, maintained routing contract, and world-class research governance/JIT refresh integration.",
        "",
        "| Agent | Static readiness | Structural status | Behavioral benchmark | External comparative benchmark |",
        "|---|---:|---|---|---|",
    ]
    for agent, score, ok, _ in rows:
        lines.append(f"| `{agent}` | {score}/100 | {'PASS' if ok else 'FAIL'} | NOT_RUN | NOT_RUN |")

    passed = sum(1 for _, _, ok, _ in rows if ok)
    lines += [
        "",
        "## Summary",
        "",
        f"- Structural readiness: **{passed}/{len(AGENTS)} PASS**.",
        "- Behavioral championship suite: **NOT_RUN** in this static validator.",
        "- SWE-bench/BFCL/HELM/WebArena-style comparative runs: **NOT_RUN** unless a pinned runtime/model/tool harness actually executes them.",
        "- `PRODUCTION_VERIFIED` and `BENCHMARKED_FRONTIER_CANDIDATE` remain evidence-based task/runtime states; this file cannot grant either state by itself.",
        "",
        "## Failure details",
        "",
    ]
    failures = []
    for agent, score, ok, checks in rows:
        if not ok:
            missing = ", ".join(name for name, passed_check in checks.items() if not passed_check)
            failures.append(f"- `{agent}`: {score}/100; missing: {missing}")
    lines.extend(failures or ["- None."])
    lines.append("")
    lines.append("Generated by `scripts/validate_agent_scoreboard.py`; CI fails if this generated scoreboard drifts from repository contracts.")
    lines.append("")
    return "\n".join(lines), all_ok


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail when the committed scoreboard differs from generated output")
    parser.add_argument("--write", action="store_true", help="Write docs/evals/AGENT_SCOREBOARD.md")
    args = parser.parse_args()

    output, all_ok = build_scoreboard()
    target = ROOT / "docs/evals/AGENT_SCOREBOARD.md"

    if args.write:
        target.write_text(output, encoding="utf-8")

    if args.check:
        committed = target.read_text(encoding="utf-8") if target.exists() else ""
        if committed != output:
            print("AGENT_SCOREBOARD.md is stale. Run: python3 scripts/validate_agent_scoreboard.py --write", file=sys.stderr)
            return 2

    print(output)
    return 0 if all_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
